### ISSUE TITLE
Apply for Alpine Linux

### ISSUE THREAD

**Issue by qaqland** [Darin755/browser-linux#10]
Thank you for your work!

Alpine Linux is also small and a lot of people use it.

**Comment by Darin755** [comment]
Alpine Linux is currently a work in progress. The biggest issues is speed and size.

If you want alpine you can always create a chroot in the main image.

To start, download the mini root filesystem from the [downloads page](https://www.alpinelinux.org/downloads). After the download is complete you need to upload the file into browser linux. I would copy it into your home directory as it will upload to /home

After that is completed you need to decompress the image with tar and gz. You can do it will the following commands:
```
mkdir alpine
cp alpine.tar.gz alpine
cd alpine
gz -d alpine.tar.gz
tar -xf alpine.tar
```

After that its just a matter of chroot

If you have any ideas for how to package a alpine image please let me know

**Comment by qaqland** [comment]
I'm sorry I don't know much about it.

Looking forward to your progress :D

**Comment by SuperMaxusa** [comment]
@Darin755 As far as I understand, this rootfs can be used as an initrd, for example, as described here: https://gist.github.com/gdamjan/1f260b58eb9fb1ba62d2234958582405

I found one implementation (https://github.com/xming/alpine-v86), but it uses an old version. Most likely, the kernel without modules is used here, although I did not find the kernel config.

**Comment by Darin755** [comment]
Hello, 

Thanks for your reply. I am currently working on a buildroot config that boots into a alpine chroot/container. I have made some progress but the hardest think is getting it to boot within 20 sec

**Comment by Darin755** [comment]
Update: I've started work on this again and I am using docker to launch a alpine image. Docker isn't working in my buildroot but I think that's due to the custom kernel.

I think I might be close

**Comment by Darin755** [comment]
I am closing this as not planned
