### ISSUE TITLE
Characters not properly displayed

### ISSUE THREAD

**Issue by Phistomevel** [Darin755/browser-linux#14]
(using firefox version 129.0.2 (64-Bit))
Hey, i opened this project via this site (i assume it's yours):
https://browser-os1.netlify.app/
and the characters of the terminal all seem to be rendered incorrectly(see the screenshot)
All the characters look like those, except for the highlighted one in the active line(the "s" in the Screenshot)
![grafik](https://github.com/user-attachments/assets/7d4c2ea7-e219-4b8b-b273-cc64d63ac3bc)

**Comment by Darin755** [comment]
That is not mine. 

However, it looks like you are using Firefox resist fingerprinting. You need to allow webGL in order for the terminal to render properly.
