### ISSUE TITLE
Add bash-static

### ISSUE THREAD

**Issue by hello-smile6** [Darin755/browser-linux#5]
You can get a static `bash` binary from https://deb.debian.org/debian/pool/main/b/bash/ , could you add it? (And neofetch? )

**Comment by Darin755** [comment]
So neofetch is quiet large and runs pretty slow. I have pfetch installed which is much faster to run. I will have to look at bash. For the time being ash should be able to do most of the things bash can.

**Comment by Darin755** [comment]
I don't see any benefit in including neofetch.
![Screenshot from 2022-05-25 10-06-56](https://user-images.githubusercontent.com/54958995/170308449-499a4f39-2039-46a2-b0dc-4087ed779e21.png)
![Screenshot from 2022-05-25 10-07-11](https://user-images.githubusercontent.com/54958995/170308450-559af3f2-d29d-4ec1-93ee-ba02b433191b.png)

**Comment by Darin755** [comment]
After giving it some though I have decided to add neofetch
